algoritmo "Exercicio 5"
// Função :   Faça o mesmo que antes, porém, ao invés de ler 10 números, o programa deverá ler e somar números até que o valor digitado seja zero ( 0 ).
// Autor :       Brian Souza Dos Santos
// Data : 12/09/2022
// Seção de Declarações 
var
contador,numero,soma:inteiro

inicio

repita
escreval ("Digite um numero: ")
leia(numero)
soma<- soma+numero
ate numero=0
escreval("a SOMA DOS NUMEROS É ",soma)
fimpara
fimalgoritmo
