algoritmo "semnome"
// Função :  Faça um algoritmo que escreva na tela os números de um número inicial a um número final. Os números inicial e final devem ser informados pelo usuário.
var
numini, numfini, a:inteiro
inicio
escreval("digite um numero")
leia(numini)
escreval("digite outro numero")
leia(numfini)
// Seção de Comandos
para a de numini ate numfini faca
escreva(a)
fimpara
fimalgoritmo
