algoritmo "exercicio8"
// Função : O programa deverá ler uma altura para cada um dos jogadores e, ao final, informar a altura média do time.
var
time: inteiro
altura, media, soma: real

inicio
para time de 1 ate 6 faca
     escreval("Digite a altura:")
     leia(altura)
     soma <- soma + altura
fimpara

     media <- soma/6
     escreval("A altura média do time é:", media)

fimalgoritmo
